# Fornex Cloud NVMe 2 VPS, Germany (order #34-353004, IP 79.132.143.145).
# Purpose: nothing but an SSH relay/jump host, so the desktop and laptop stay
# reachable from mobile networks where direct/WireGuard connectivity is
# unreliable (see mynotes/vps-ssh-relay-session/ for the full reasoning).
#
# Installed via nixos-anywhere against the stock Ubuntu image:
#   nix run github:nix-community/nixos-anywhere -- \
#     --flake .#vps-relay root@79.132.143.145
#
# hardware-configuration.nix here is hand-written (generic KVM/virtio), not
# generated by nixos-generate-config - there was no NixOS system to generate
# it from before the install. Revisit if nixos-anywhere's own hardware-config
# detection produces something different.
{ config, lib, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix
  ];

  networking.hostName = "vps-relay";

  # ---------- boot: BIOS/GPT, single virtio disk ----------
  # device = "/dev/vda" is NOT set here - disko.nix already supplies
  # boot.loader.grub.devices from the disk's EF02 (BIOS boot) partition.
  # Setting it again here duplicated the entry and tripped NixOS's
  # "no duplicated devices in mirroredBoots" assertion.
  boot.loader.grub = {
    enable = true;
    efiSupport = false;
  };

  # ---------- network: static, matches Fornex's actual assignment ----------
  # Confirmed live on the stock Ubuntu image before wiping it (ip -brief addr,
  # ip route, /etc/netplan/*.yaml) - eth0, not the ensX/enpXsY predictable
  # naming NixOS defaults to, so predictable naming is disabled below to match.
  networking.usePredictableInterfaceNames = false;
  networking.useDHCP = false;

  networking.interfaces.eth0.ipv4.addresses = [
    { address = "79.132.143.145"; prefixLength = 24; }
  ];
  networking.interfaces.eth0.ipv6.addresses = [
    { address = "2a02:6b40:2000:1766::1"; prefixLength = 48; }
  ];
  networking.defaultGateway = "79.132.143.1";
  networking.defaultGateway6 = { address = "2a02:6b40:2000::1"; interface = "eth0"; };
  networking.nameservers = [
    "91.228.153.88"
    "195.26.237.237"
    "31.172.68.71"
  ];

  # ---------- ssh ----------
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "prohibit-password";   # key-only, no root password login
    };
  };

  # Root logs in directly here (no separate user - this box does one job).
  # Both keys already used for desktop <-> laptop; see
  # mynotes/ssh-desktop-to-laptop-session/01-walkthrough.md.
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOGVxSVVSTPgXZjoUUukEmeGfyAdhQPmTms3VA1S2wm+ yuri@nixos-to-laptop"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIECbpIHIwBlUH93dvm+O/IZbUSASdwffhtQum58VWuKS yuri@ubuntu-desktop"
  ];

  networking.firewall.allowedTCPPorts = [ 22 ];

  environment.systemPackages = with pkgs; [
    tmux
  ];

  # Never change this after install - it is not a "latest version" knob.
  system.stateVersion = "26.05";
}
